#!/bin/bash
# Find the PID of the 4-to_infinity_and_beyond process and stop it without using kill or killall

# Get the PID of the process
pid=$(pgrep -f 4-to_infinity_and_beyond)

# Stop it by writing to /proc (equivalent to SIGTERM)
if [ -n "$pid" ]; then
    echo "Terminating process $pid"
    # Sending SIGTERM by writing to /proc
    # This is like: kill -15 $pid
    echo 15 > /proc/$pid/sig
fi
