#!/usr/bin/env bash
# Stops the 4-to_infinity_and_beyond process without using kill or killall

# Find PIDs and terminate each process using Perl's kill function
ps aux | grep "[4]-to_infinity_and_beyond" | awk '{print $2}' | while read -r PID; do
  if [ -n "$PID" ]; then
    perl -e "kill 'TERM', $PID"
  fi
done
